import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      {" "}
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>{" "}
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        {" "}
        This project was generated By{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          {" "}
          Dhiwise{" "}
        </a>{" "}
        . Quickly use below links to navigate through all pages.{" "}
      </p>{" "}
      <ul style={{ listStyle: "none", padding: "0" }}>
        {" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/heroone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            HeroOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link to="/shop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            {" "}
            Shop{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/productone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ProductOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/cartone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CartOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/checkoutaddress"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CheckoutAddress{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/checkoutshipping"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CheckoutShipping{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/checkoutpayment"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CheckoutPayment{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/login"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Login{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/reviews"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Reviews{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/productpagetwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ProductPageTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/loginemail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            LoginEmail{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/herotwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            HeroTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/shopone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ShopOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/footer"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Footer{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/simple"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Simple{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/simpleone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            SimpleOne{" "}
          </Link>{" "}
        </li>{" "}
      </ul>{" "}
    </div>
  );
};
export default Home;
